name: build-tag-deploy
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build-tag-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Set-up User ðŸµ
        uses: fregante/setup-git-user@v2

      - name: Bump and Tag ðŸ·ï¸
        run: |
          npm version patch
          git tag "$(cat package.json | jq -r '.version')" -m "[release] planetary-defence-$(cat package.json | jq -r '.version')"
          git push origin "$(cat package.json | jq -r '.version')"
          echo "VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

          npm version patch --git-tag-version false --force
          echo "SNAPSHOT_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
          git stash
        # Note :: an env var cannot be accessed from a step that defines or updates it

      - name: Release ðŸ“¦
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}

      - name: Add -SNAPSHOT ðŸ“·
        run: |
          npm version ${{ env.SNAPSHOT_VERSION }}-SNAPSHOT
          git stash pop

      - name: Commit -SNAPSHOT ðŸ’¾
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: src
